<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\DeliveryStatus;

class DeliveryStatusSeeder extends Seeder
{

    public function run()
    {
        $arr_seeders = [
          [
            [
             "ds_num" => "V02503214123644",
             "ds_line" => "1",
             "po_line_id" => "1",
             "po_release" => "0",
             "description" => "SUB,ASSY CONNECTING ROD EA11-N",
             "unit_price" => "104260",
             "tax_status" => "PPN10",
             "shipped_qty" => "1075",
             "received_qty" => "1075",
             "rejected_qty" => "0",
             "bank" => "BCA",
             "petugas_vendor" => "",
             "no_surat_jalan_vendor" => "",
            ],
            ["ds_num" => "V02503214123644"],
          ],
          [
            [
             "ds_num" => "V02503214123524",
             "ds_line" => "3",
             "po_line_id" => "6",
             "po_release" => "0",
             "description" => "SUB, ASSY CONNECTING ROD EA8-N",
             "unit_price" => "104260",
             "tax_status" => "PPN10",
             "shipped_qty" => "1055",
             "received_qty" => "1035",
             "rejected_qty" => "20",
             "bank" => "BCA",
             "petugas_vendor" => "",
             "no_surat_jalan_vendor" => "",
            ],
            ["ds_num" => "V02503214123524"],
          ],
          [
            [
             "ds_num" => "V02503214123524",
             "ds_line" => "2",
             "po_line_id" => "5",
             "po_release" => "0",
             "description" => "SUB,ASSY CONNECTING ROD EA11-N",
             "unit_price" => "104260",
             "tax_status" => "PPN10",
             "shipped_qty" => "75",
             "received_qty" => "70",
             "rejected_qty" => "5",
             "bank" => "BCA",
             "petugas_vendor" => "",
             "no_surat_jalan_vendor" => "",
            ],
            ["ds_num" => "V02503214123524"],
          ],
          [
            [
             "ds_num" => "V02503214123524",
             "ds_line" => "1",
             "po_line_id" => "4",
             "po_release" => "0",
             "description" => "SUB,ASSY CONNECTING ROD EA14-N",
             "unit_price" => "104260",
             "tax_status" => "PPN10",
             "shipped_qty" => "1075",
             "received_qty" => "1075",
             "rejected_qty" => "0",
             "bank" => "BCA",
             "petugas_vendor" => "",
             "no_surat_jalan_vendor" => "",
            ],
            ["ds_num" => "V02503214123524"],
          ],
          [
            [
             "ds_num" => "V02503214123425",
             "ds_line" => "3",
             "po_line_id" => "1",
             "po_release" => "0",
             "description" => "SUB,ASSY CONNECTING ROD EA11-N",
             "unit_price" => "104260",
             "tax_status" => "PPN10",
             "shipped_qty" => "1075",
             "received_qty" => "1075",
             "rejected_qty" => "0",
             "bank" => "BCA",
             "petugas_vendor" => "",
             "no_surat_jalan_vendor" => "",
            ],
            ["ds_num" => "V02503214123425"],
          ],
          [
            [
             "ds_num" => "V02503214123425",
             "ds_line" => "2",
             "po_line_id" => "3",
             "po_release" => "0",
             "description" => "SUB, ASSY CONNECTING ROD EA8-N",
             "unit_price" => "104260",
             "tax_status" => "PPN10",
             "shipped_qty" => "1075",
             "received_qty" => "1075",
             "rejected_qty" => "0",
             "bank" => "BCA",
             "petugas_vendor" => "",
             "no_surat_jalan_vendor" => "",
            ],
            ["ds_num" => "V02503214123425"],
          ],
          [
            [
             "ds_num" => "V02503214123425",
             "ds_line" => "1",
             "po_line_id" => "2",
             "po_release" => "0",
             "description" => "SUB,ASSY CONNECTING ROD EA14-N",
             "unit_price" => "104260",
             "tax_status" => "PPN10",
             "shipped_qty" => "1075",
             "received_qty" => "1075",
             "rejected_qty" => "0",
             "bank" => "BCA",
             "petugas_vendor" => "",
             "no_surat_jalan_vendor" => "",
            ],
            ["ds_num" => "V02503214123425"],
          ],
          [
            [
             "ds_num" => "V02503214123341",
             "ds_line" => "1",
             "po_line_id" => "1",
             "po_release" => "0",
             "description" => "SUB,ASSY CONNECTING ROD EA11-N",
             "unit_price" => "104260",
             "tax_status" => "PPN10",
             "shipped_qty" => "1075",
             "received_qty" => "1075",
             "rejected_qty" => "0",
             "bank" => "BCA",
             "petugas_vendor" => "",
             "no_surat_jalan_vendor" => "",
            ],
            ["ds_num" => "V02503214123341"],
          ],
          [
            [
             "ds_num" => "V02026115031662",
             "ds_line" => "1",
             "po_line_id" => "1",
             "po_release" => "0",
             "description" => "OHM SAKLAR (63 A 4P)",
             "unit_price" => "104260",
             "tax_status" => "PPN10",
             "shipped_qty" => "1075",
             "received_qty" => "1075",
             "rejected_qty" => "0",
             "bank" => "BCA",
             "petugas_vendor" => "",
             "no_surat_jalan_vendor" => "",
            ],
            ["ds_num" => "V02026115031662"],
          ],
          [
            [
             "ds_num" => "V02025115021267",
             "ds_line" => "1",
             "po_line_id" => "1",
             "po_release" => "0",
             "description" => "FUEL GAUGE PIPE DIA 5.5 X 8",
             "unit_price" => "104260",
             "tax_status" => "PPN10",
             "shipped_qty" => "1075",
             "received_qty" => "1075",
             "rejected_qty" => "0",
             "bank" => "BCA",
             "petugas_vendor" => "",
             "no_surat_jalan_vendor" => "",
            ],
            ["ds_num" => "V02025115021267"],
          ],
          [
            [
             "ds_num" => "V02024315042357",
             "ds_line" => "4",
             "po_line_id" => "4",
             "po_release" => "0",
             "description" => "PACK. SP. KECIL RD110 DI-2T/RD85DI-S",
             "unit_price" => "104260",
             "tax_status" => "PPN10",
             "shipped_qty" => "1075",
             "received_qty" => "1075",
             "rejected_qty" => "0",
             "bank" => "BCA",
             "petugas_vendor" => "",
             "no_surat_jalan_vendor" => "",
            ],
            ["ds_num" => "V02024315042357"],
          ],
          [
            [
             "ds_num" => "V02024315042357",
             "ds_line" => "3",
             "po_line_id" => "3",
             "po_release" => "0",
             "description" => "PACK. SP. BESAR RD110 DI-2T/RD85DI-S",
             "unit_price" => "104260",
             "tax_status" => "PPN10",
             "shipped_qty" => "1075",
             "received_qty" => "1075",
             "rejected_qty" => "0",
             "bank" => "BCA",
             "petugas_vendor" => "",
             "no_surat_jalan_vendor" => "",
            ],
            ["ds_num" => "V02024315042357"],
          ],
          [
            [
             "ds_num" => "V02024315042357",
             "ds_line" => "2",
             "po_line_id" => "2",
             "po_release" => "0",
             "description" => "PACK. LANDASAN  RD110 DI-2T/RD85DI-S",
             "unit_price" => "104260",
             "tax_status" => "PPN10",
             "shipped_qty" => "95",
             "received_qty" => "92",
             "rejected_qty" => "3",
             "bank" => "BCA",
             "petugas_vendor" => "",
             "no_surat_jalan_vendor" => "",
            ],
            ["ds_num" => "V02024315042357"],
          ],
          [
            [
             "ds_num" => "V02024315042357",
             "ds_line" => "1",
             "po_line_id" => "1",
             "po_release" => "0",
             "description" => "PACK. TUTUP RD110 DI-2T/RD85DI-S",
             "unit_price" => "104260",
             "tax_status" => "PPN10",
             "shipped_qty" => "1075",
             "received_qty" => "1075",
             "rejected_qty" => "0",
             "bank" => "BCA",
             "petugas_vendor" => "",
             "no_surat_jalan_vendor" => "",
            ],
            ["ds_num" => "V02024315042357"],
          ],
          [
            [
             "ds_num" => "V02024315042287",
             "ds_line" => "8",
             "po_line_id" => "3",
             "po_release" => "0",
             "description" => "PACK. SP. KECIL RD110 DI-2T",
             "unit_price" => "104260",
             "tax_status" => "PPN10",
             "shipped_qty" => "65",
             "received_qty" => "60",
             "rejected_qty" => "5",
             "bank" => "BCA",
             "petugas_vendor" => "",
             "no_surat_jalan_vendor" => "",
            ],
            ["ds_num" => "V02024315042287"],
          ],
          [
            [
             "ds_num" => "V02024315042287",
             "ds_line" => "7",
             "po_line_id" => "5",
             "po_release" => "0",
             "description" => "PACK. SP. BESAR RD110 DI-2T",
             "unit_price" => "104260",
             "tax_status" => "PPN10",
             "shipped_qty" => "45",
             "received_qty" => "45",
             "rejected_qty" => "0",
             "bank" => "BCA",
             "petugas_vendor" => "",
             "no_surat_jalan_vendor" => "",
            ],
            ["ds_num" => "V02024315042287"],
          ],
          [
            [
             "ds_num" => "V02024315042287",
             "ds_line" => "6",
             "po_line_id" => "1",
             "po_release" => "0",
             "description" => "PACK. TUTUP    RD110 DI-2T",
             "unit_price" => "104260",
             "tax_status" => "PPN10",
             "shipped_qty" => "1075",
             "received_qty" => "1075",
             "rejected_qty" => "0",
             "bank" => "BCA",
             "petugas_vendor" => "",
             "no_surat_jalan_vendor" => "",
            ],
            ["ds_num" => "V02024315042287"],
          ],
          [
            [
             "ds_num" => "V02024315042287",
             "ds_line" => "5",
             "po_line_id" => "4",
             "po_release" => "0",
             "description" => "PACK. LANDASAN  RD110 DI-2T",
             "unit_price" => "104260",
             "tax_status" => "PPN10",
             "shipped_qty" => "1075",
             "received_qty" => "1075",
             "rejected_qty" => "0",
             "bank" => "BCA",
             "petugas_vendor" => "",
             "no_surat_jalan_vendor" => "",
            ],
            ["ds_num" => "V02024315042287"],
          ],
          [
            [
             "ds_num" => "V02024315042287",
             "ds_line" => "4",
             "po_line_id" => "4",
             "po_release" => "0",
             "description" => "PACK. SP. KECIL RD110 DI-2T/RD85DI-S",
             "unit_price" => "104260",
             "tax_status" => "PPN10",
             "shipped_qty" => "1075",
             "received_qty" => "1075",
             "rejected_qty" => "0",
             "bank" => "BCA",
             "petugas_vendor" => "",
             "no_surat_jalan_vendor" => "",
            ],
            ["ds_num" => "V02024315042287"],
          ],
          [
            [
             "ds_num" => "V02024315042287",
             "ds_line" => "3",
             "po_line_id" => "3",
             "po_release" => "0",
             "description" => "PACK. SP. BESAR RD110 DI-2T/RD85DI-S",
             "unit_price" => "104260",
             "tax_status" => "PPN10",
             "shipped_qty" => "1075",
             "received_qty" => "1075",
             "rejected_qty" => "0",
             "bank" => "BCA",
             "petugas_vendor" => "",
             "no_surat_jalan_vendor" => "",
            ],
            ["ds_num" => "V02024315042287"],
          ],
        ];

       foreach($arr_seeders as $key => $seed) {
          DeliveryStatus::updateOrCreate($seed[0],$seed[1]);
       }
    }
}