<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PurchaseOrderLine;

class PurchaseOrderLineSeeder extends Seeder
{

    public function run()
    {
        $arr_seeders = [
          [
            [
             "po_num" => "PU00006434",
             "po_line" => "1",
             "po_release" => "0",
             "item" => "55330500/0424",
             "item_ptki" => "",
             "w_serial" => "",
             "description" => "S PLAT 1/4 X 2' X 6 M",
             "po_change" => "0",
             "order_qty" => "4",
             "inspection_flag" => "0",
             "u_m" => "PC",
             "due_date" => "2014-12-16 00:00:00",
             "unit_price" => "210000",
             "wh" => "P1",
             "location" => "",
             "tax_status" => "NOTAX",
             "currency" => "IDR",
             "item_alias" => "",
             "status" => "O",
             "accept_flag" => "1",
             "reason" => "",
             "read_by" => "1",
             "read_at" => "2021-10-29 11:58:44",
            ],
            [
              "po_num" => "PU00006434",
            "po_line" => "1",],
          ],
          [
            [
             "po_num" => "PU00006434",
             "po_line" => "2",
             "po_release" => "0",
             "item" => "0084A-00009-420-2",
             "item_ptki" => "",
             "w_serial" => "",
             "description" => "EMULCUT 500-A",
             "po_change" => "0",
             "order_qty" => "200",
             "inspection_flag" => "0",
             "u_m" => "KG",
             "due_date" => "2015-03-16 00:00:00",
             "unit_price" => "54900",
             "wh" => "P1",
             "location" => "O2-50602",
             "tax_status" => "PPN10",
             "currency" => "IDR",
             "item_alias" => "",
             "status" => "O",
             "accept_flag" => "2",
             "reason" => "",
             "read_by" => "1",
             "read_at" => "2021-10-29 12:00:52",
            ],
            ["po_num" => "PU00006434",
            "po_line" => "2",],
          ],
          [
            [
             "po_num" => "PU00006434",
             "po_line" => "3",
             "po_release" => "0",
             "item" => "0084A-00009-420-2",
             "item_ptki" => "",
             "w_serial" => "",
             "description" => "EMULCUT 500-A",
             "po_change" => "1",
             "order_qty" => "120",
             "inspection_flag" => "0",
             "u_m" => "KG",
             "due_date" => "2015-04-16 00:00:00",
             "unit_price" => "54900",
             "wh" => "P1",
             "location" => "O2-50602",
             "tax_status" => "PPN10",
             "currency" => "IDR",
             "item_alias" => "",
             "status" => "O",
             "accept_flag" => "2",
             "reason" => "",
             "read_by" => "1",
             "read_at" => "2021-10-29 12:00:52",
            ],
            ["po_num" => "PU00006434",
            "po_line" => "3",],
          ],
          [
            [
             "po_num" => "PU00006434",
             "po_line" => "4",
             "po_release" => "0",
             "item" => "0084A-00021-420-2",
             "item_ptki" => "",
             "w_serial" => "",
             "description" => "PAY OFF METCLEAN LS",
             "po_change" => "0",
             "order_qty" => "100",
             "inspection_flag" => "0",
             "u_m" => "LT",
             "due_date" => "2015-03-16 00:00:00",
             "unit_price" => "31000",
             "wh" => "P1",
             "location" => "O2-50602",
             "tax_status" => "PPN10",
             "currency" => "IDR",
             "item_alias" => "",
             "status" => "C",
             "accept_flag" => "2",
             "reason" => "",
             "read_by" => "1",
             "read_at" => "2021-10-29 12:00:52",
            ],
            ["po_num" => "PU00006434",
            "po_line" => "4",],
          ],
          [
            [
             "po_num" => "PU00006435",
             "po_line" => "1",
             "po_release" => "0",
             "item" => "0092C-00008-425-2",
             "item_ptki" => "",
             "w_serial" => "",
             "description" => "PROPEEL",
             "po_change" => "0",
             "order_qty" => "100",
             "inspection_flag" => "0",
             "u_m" => "LT",
             "due_date" => "2015-03-16 00:00:00",
             "unit_price" => "70000",
             "wh" => "P1",
             "location" => "O2-50602",
             "tax_status" => "PPN10",
             "currency" => "IDR",
             "item_alias" => "",
             "status" => "O",
             "accept_flag" => "0",
             "reason" => "",
             "read_by" => "",
            ],
            ["po_num" => "PU00006435",
            "po_line" => "1",],
          ],
          [
            [
             "po_num" => "PU00006435",
             "po_line" => "2",
             "po_release" => "0",
             "item" => "0084A-00019-420-2",
             "item_ptki" => "",
             "w_serial" => "",
             "description" => "UNINEAT CUTTING OIL",
             "po_change" => "0",
             "order_qty" => "600",
             "inspection_flag" => "0",
             "u_m" => "LT",
             "due_date" => "2015-03-16 00:00:00",
             "unit_price" => "27000",
             "wh" => "P1",
             "location" => "O2-50602",
             "tax_status" => "PPN10",
             "currency" => "IDR",
             "item_alias" => "",
             "status" => "O",
             "accept_flag" => "0",
             "reason" => "",
             "read_by" => "",
            ],
            ["po_num" => "PU00006435",
            "po_line" => "2",],
          ],
          [
            [
             "po_num" => "PU00006435",
             "po_line" => "3",
             "po_release" => "0",
             "item" => "0084A-00021-420-2",
             "item_ptki" => "",
             "w_serial" => "",
             "description" => "PAY OFF METCLEAN LS",
             "po_change" => "0",
             "order_qty" => "23",
             "inspection_flag" => "0",
             "u_m" => "LT",
             "due_date" => "2015-03-16 00:00:00",
             "unit_price" => "21000",
             "wh" => "P1",
             "location" => "O2-50602",
             "tax_status" => "PPN10",
             "currency" => "IDR",
             "item_alias" => "",
             "status" => "O",
             "accept_flag" => "0",
             "reason" => "",
             "read_by" => "",
            ],
            ["po_num" => "PU00006435",
            "po_line" => "3",],
          ],
          [
            [
             "po_num" => "PU00006434",
             "po_line" => "5",
             "po_release" => "0",
             "item" => "0084A-00021-420-2",
             "item_ptki" => "",
             "w_serial" => "",
             "description" => "PAY OFF METCLEAN LS",
             "po_change" => "0",
             "order_qty" => "33",
             "inspection_flag" => "0",
             "u_m" => "LT",
             "due_date" => "2015-03-16 00:00:00",
             "unit_price" => "41000",
             "wh" => "P1",
             "location" => "O2-50602",
             "tax_status" => "PPN10",
             "currency" => "IDR",
             "item_alias" => "",
             "status" => "F",
             "accept_flag" => "1",
             "reason" => "",
             "read_by" => "1",
             "read_at" => "2021-10-29 12:06:24",
            ],
            ["po_num" => "PU00006434",
            "po_line" => "5",],
          ],
          [
            [
              "po_num" => "PU00006436",
              "po_line" => "1",
              "po_release" => "0",
              "item" => "0084A-00021-420-2",
              "item_ptki" => "",
              "w_serial" => "",
              "description" => "PAY OFF METCLEAN XLS",
              "po_change" => "0",
              "order_qty" => "33",
              "inspection_flag" => "0",
              "u_m" => "LT",
              "due_date" => "2015-03-16 00:00:00",
              "unit_price" => "41000",
              "wh" => "P1",
              "location" => "O2-50602",
              "tax_status" => "PPN10",
              "currency" => "IDR",
              "item_alias" => "",
              "status" => "C",
              "accept_flag" => "1",
              "reason" => "",
              "read_by" => "1",
              "read_at" => "2021-10-29 12:06:24",
            ],
            ["po_num" => "PU00006436",
            "po_line" => "1",],
          ],
          [
            [
             "po_num" => "PU00006436",
             "po_line" => "2",
             "po_release" => "0",
             "item" => "0084A-00021-420-2",
             "item_ptki" => "",
             "w_serial" => "",
             "description" => "PAY OFF METCSS XLS",
             "po_change" => "0",
             "order_qty" => "33",
             "inspection_flag" => "0",
             "u_m" => "LT",
             "due_date" => "2015-03-16 00:00:00",
             "unit_price" => "41000",
             "wh" => "P1",
             "location" => "O2-50602",
             "tax_status" => "PPN10",
             "currency" => "IDR",
             "item_alias" => "",
             "status" => "O",
             "accept_flag" => "1",
             "reason" => "",
             "read_by" => "1",
             "read_at" => "2021-10-29 12:06:24",
            ],
            ["po_num" => "PU00006436",
            "po_line" => "2",],
          ],
          [
            [
              "po_num" => "PU00006436",
              "po_line" => "3",
              "po_release" => "0",
              "item" => "0084A-00021-420-2",
              "item_ptki" => "",
              "w_serial" => "",
              "description" => "PAY OFF METCSS XLS",
              "po_change" => "0",
              "order_qty" => "33",
              "inspection_flag" => "0",
              "u_m" => "LT",
              "due_date" => "2015-03-16 00:00:00",
              "unit_price" => "41000",
              "wh" => "P1",
              "location" => "O2-50602",
              "tax_status" => "PPN10",
              "currency" => "IDR",
              "item_alias" => "",
              "status" => "O",
              "accept_flag" => "0",
              "reason" => "",
              "read_by" => "",
            ],
            ["po_num" => "PU00006436",
            "po_line" => "3",],
          ],
          [
            [
              "po_num" => "PU00006425",
              "po_line" => "1",
              "po_release" => "0",
              "item" => "0084A-00021-420-2",
              "item_ptki" => "",
              "w_serial" => "",
              "description" => "AA OFF METCSS XLS",
              "po_change" => "0",
              "order_qty" => "33",
              "inspection_flag" => "0",
              "u_m" => "LT",
              "due_date" => "2015-03-16 00:00:00",
              "unit_price" => "41000",
              "wh" => "P1",
              "location" => "O2-50602",
              "tax_status" => "PPN10",
              "currency" => "IDR",
              "item_alias" => "",
              "status" => "O",
              "accept_flag" => "0",
              "reason" => "",
              "read_by" => "",
            ],
            [ "po_num" => "PU00006425",
            "po_line" => "1",],
          ],
        ];

       foreach($arr_seeders as $key => $seed) {
          PurchaseOrderLine::updateOrCreate($seed[0],$seed[1]);
       }
    }
}